apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: main-street-migrator
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/ingress: all
    spec:
      serviceAccountName: msm-runtime@${PROJECT_ID}.iam.gserviceaccount.com
      containers:
      - image: ${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/${AR_REPO}/${SERVICE_NAME}:${GITHUB_SHA}
        ports:
        - containerPort: 5003
        env:
        - name: PORT
          value: "5003"
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
        startupProbe:
          httpGet:
            path: /api/health
            port: 5003
          initialDelaySeconds: 10
          periodSeconds: 10
      traffic:
      - percent: 100
        latestRevision: true
